### ISSUE TITLE
Missing argument

### ISSUE THREAD

**Issue by XemBryan** [DanMcInerney/Invoke-Cats#2]
I'm loading to memory:

IEX (New-Object Net.WebClient).DownloadString('C:\Users\aki\Desktop\new\Invoke-Cats.ps1')
and then executing Invoke-Catspass the hash with command:

PS C:\Users\Administrator> Invoke-Cats-Command 'sekurlsa::pth /user:Administrator /domain:CISCO /NTLM:someNTLM'
returns an error:

ERROR kuhl_m_sekurlsa_pth ; Missing argument : user
But the argument is there. It happens on W2012

So the question is: how to write Cats command in Powershell to not complaint about arguments?

**Comment by DanMcInerney** [comment]
This script is just Invoke-Mimikatz with function names changed and run through Invoke-Obfuscation. It needs to be run through Invoke-Obfuscation every few weeks and then tested which takes a while. I haven't done that in a while so that's why this is happening probably. I don't need to use this script for a while so I probably won't fix it until I need it again.
